nome = str(input("Digite o seu nome completo?:")).strip()
maisculas = nome.upper()
minusculas = nome.lower()
letras = len(nome.replace(" ", ""))
letras2 = len(nome.split()[0])
print("Nome completo em maiscúlo: {}".format(maisculas))
print("Nome completo em minúsculo: {}".format(minusculas))
print("Quantas letras tem o nome sem espaço: {}".format(letras))
print("Quantas letras tem o primeiro nome: {}".format(letras2))